"""BLE UUIDs and protocol constants for Meshtastic BLE communication.

Reference: meshtastic/firmware BLE GATT service definitions.
"""

# Meshtastic BLE Service UUID
SERVICE_UUID = "6ba1b218-15a8-461f-9fa8-5dcae273eafd"

# Characteristic UUIDs
TORADIO_UUID = "f75c76d2-129e-4dad-a1dd-7866124401e7"      # Write w/ Response
FROMRADIO_UUID = "2c55e69e-4993-11ed-b878-0242ac120002"    # Read
FROMNUM_UUID = "ed9da18c-a800-4f66-a670-aa7547e34453"      # Notify (4-byte LE uint32)
LOGRADIO_UUID = "5a3d6e49-06e6-4423-9944-e9de8cdf9547"    # Log records

# Two-stage config handshake nonces (used by both iOS and Android apps)
CONFIG_NONCE = 69420      # Stage 1: config only (MyInfo, Config, ModuleConfig, Channels)
NODEDB_NONCE = 69421      # Stage 2: node database (NodeInfo entries)

# Legacy aliases
CONFIG_REQUEST_ID = CONFIG_NONCE
NODEDB_REQUEST_ID = NODEDB_NONCE

# Hardware model IDs (subset relevant for SDR)
HW_MODEL_UNSET = 0
HW_MODEL_PORTDUINO = 37       # Linux-based device (Raspberry Pi, SDR gateway)
HW_MODEL_LINUX_NATIVE = HW_MODEL_PORTDUINO  # Alias for backward compat

# AdminMessage field numbers (from admin.proto payload_variant oneof)
ADMIN_GET_CHANNEL_REQUEST = 1
ADMIN_GET_CHANNEL_RESPONSE = 2
ADMIN_GET_OWNER_REQUEST = 3
ADMIN_GET_OWNER_RESPONSE = 4
ADMIN_GET_CONFIG_REQUEST = 5
ADMIN_GET_CONFIG_RESPONSE = 6
ADMIN_GET_MODULE_CONFIG_REQUEST = 7
ADMIN_GET_MODULE_CONFIG_RESPONSE = 8
ADMIN_GET_CANNED_MSG_REQUEST = 10
ADMIN_GET_CANNED_MSG_RESPONSE = 11
ADMIN_GET_DEVICE_METADATA_REQUEST = 12
ADMIN_GET_DEVICE_METADATA_RESPONSE = 13
ADMIN_GET_RINGTONE_REQUEST = 14
ADMIN_GET_RINGTONE_RESPONSE = 15
ADMIN_GET_DEVICE_CONN_STATUS_REQUEST = 16
ADMIN_GET_DEVICE_CONN_STATUS_RESPONSE = 17
ADMIN_SET_HAM_MODE = 18
ADMIN_GET_NODE_REMOTE_HW_PINS_REQUEST = 19
ADMIN_GET_NODE_REMOTE_HW_PINS_RESPONSE = 20
ADMIN_ENTER_DFU_MODE_REQUEST = 21
ADMIN_DELETE_FILE_REQUEST = 22
ADMIN_SET_SCALE = 23
ADMIN_BACKUP_PREFERENCES = 24
ADMIN_RESTORE_PREFERENCES = 25
ADMIN_REMOVE_BACKUP_PREFERENCES = 26
ADMIN_SEND_INPUT_EVENT = 27
ADMIN_SET_OWNER = 32
ADMIN_SET_CHANNEL = 33
ADMIN_SET_CONFIG = 34
ADMIN_SET_MODULE_CONFIG = 35
ADMIN_SET_CANNED_MSG = 36
ADMIN_SET_RINGTONE = 37
ADMIN_REMOVE_BY_NODENUM = 38
ADMIN_SET_FAVORITE_NODE = 39
ADMIN_REMOVE_FAVORITE_NODE = 40
ADMIN_SET_FIXED_POSITION = 41
ADMIN_REMOVE_FIXED_POSITION = 42
ADMIN_SET_TIME_ONLY = 43
ADMIN_GET_UI_CONFIG_REQUEST = 44
ADMIN_GET_UI_CONFIG_RESPONSE = 45
ADMIN_STORE_UI_CONFIG = 46
ADMIN_SET_IGNORED_NODE = 47
ADMIN_REMOVE_IGNORED_NODE = 48
ADMIN_TOGGLE_MUTED_NODE = 49
ADMIN_BEGIN_EDIT = 64
ADMIN_COMMIT_EDIT = 65
ADMIN_ADD_CONTACT = 66
ADMIN_KEY_VERIFICATION = 67
ADMIN_FACTORY_RESET_DEVICE = 94
ADMIN_REBOOT_OTA_SECONDS = 95
ADMIN_EXIT_SIMULATOR = 96
ADMIN_REBOOT_SECONDS = 97
ADMIN_SHUTDOWN_SECONDS = 98
ADMIN_FACTORY_RESET_CONFIG = 99
ADMIN_NODEDB_RESET = 100
ADMIN_SESSION_PASSKEY = 101
ADMIN_OTA_REQUEST = 102
ADMIN_SENSOR_CONFIG = 103

# Config type enum (AdminMessage.ConfigType)
CONFIG_DEVICE = 0
CONFIG_POSITION = 1
CONFIG_POWER = 2
CONFIG_NETWORK = 3
CONFIG_DISPLAY = 4
CONFIG_LORA = 5
CONFIG_BLUETOOTH = 6
CONFIG_SECURITY = 7
CONFIG_SESSIONKEY = 8
CONFIG_DEVICEUI = 9

# ModuleConfig type enum (AdminMessage.ModuleConfigType)
MODULE_MQTT = 0
MODULE_SERIAL = 1
MODULE_EXTNOTIF = 2
MODULE_STORE_FORWARD = 3
MODULE_RANGE_TEST = 4
MODULE_TELEMETRY = 5
MODULE_CANNED_MSG = 6
MODULE_AUDIO = 7
MODULE_REMOTE_HW = 8
MODULE_NEIGHBOR_INFO = 9
MODULE_AMBIENT_LIGHTING = 10
MODULE_DETECTION_SENSOR = 11
MODULE_PAXCOUNTER = 12
MODULE_STATUS_MESSAGE = 13
MODULE_TRAFFIC_MANAGEMENT = 14

# LoRaConfig region code <-> name mapping
REGION_CODE_MAP = {
    0: "UNSET", 1: "US", 2: "EU_433", 3: "EU_868", 4: "CN", 5: "JP",
    6: "ANZ", 7: "KR", 8: "TW", 9: "RU", 10: "IN", 11: "NZ_865",
    12: "TH", 13: "LORA_24", 14: "UA_433", 15: "UA_868", 16: "MY_433",
    17: "MY_919", 18: "SG_923", 19: "PH_433", 20: "PH_868", 21: "PH_915",
    22: "ANZ_433", 23: "KZ_433", 24: "KZ_863", 25: "NP_865", 26: "BR_902",
}
REGION_NAME_TO_CODE = {v: k for k, v in REGION_CODE_MAP.items()}

# ModemPreset enum <-> name mapping
MODEM_PRESET_MAP = {
    0: "LONG_FAST", 1: "LONG_SLOW", 2: "VERY_LONG_SLOW", 3: "MEDIUM_SLOW",
    4: "MEDIUM_FAST", 5: "SHORT_SLOW", 6: "SHORT_FAST", 7: "LONG_MODERATE",
    8: "SHORT_TURBO", 9: "LONG_TURBO",
}
PRESET_NAME_TO_CODE = {v: k for k, v in MODEM_PRESET_MAP.items()}
